### ISSUE TITLE
MakeClothes2 crashed when creating clothes

### ISSUE THREAD

**Issue by virgil382** [makehumancommunity/makehuman#134]
Traceback (most recent call last):
File "C:\.....\scripts\Blender\2.83\scripts\addons\makeclothes\operators\createclothes.py", line 54, in execute
bpy.aps.object.select_all(action='DESELECT')
File "G:\....\2.83\scripts\modules\bpy\ops.py", line 201, in __call__
  ...

**Comment by Aranuvir** [comment]
A) it's a duplicate and B) it's the wrong burg tracker.
Finally this issue massage isn't helpful at all. We need more information about the version of the plug-in and the full traceback.
Please report to the correct bug tracker. Thank you.
Closing the issue here...
