### ISSUE TITLE
windows 10, fails

### ISSUE THREAD

**Issue by qwabra** [makehumancommunity/makehuman#168]
- MK dir `C:\MH`
- cd 
- `git clone https://github.com/makehumancommunity/makehuman.git ./`
- `PS C:\MH> .\.env\Scripts\python.exe -m pip install -r requirements.txt`

```bash
PS C:\MH> .\.env\Scripts\python.exe .\makehuman\makehuman.py 
MakeHuman Copyright (C) 2001-2020 http://www.makehumancommunity.org
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it      
under certain conditions. For details use the option --license     

Traceback (most recent call last):
  File "C:\MH\.env\lib\site-packages\OpenGL\latebind.py", line 43, in __call__
    return self._finalCall( *args, **named )
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\MH\makehuman\./lib\qtui.py", line 295, in initializeGL
    gl.OnInit()
  File "C:\MH\makehuman\./lib\glmodule.py", line 316, in OnInit
    glLightModelfv(GL_LIGHT_MODEL_AMBIENT, A(0.0, 0.0, 0.0, 1.0))
  File "C:\MH\.env\lib\site-packages\OpenGL\latebind.py", line 47, in __call__
    return self._finalCall( *args, **named )
  File "C:\MH\.env\lib\site-packages\OpenGL\wrapper.py", line 700, in wrapperCall
    raise err
    result = wrappedOperation( *cArguments )
  File "C:\MH\.env\lib\site-packages\OpenGL\platform\baseplatform.py", line 415, in __call__
    return self( *args, **named )
  File "C:\MH\.env\lib\site-packages\OpenGL\error.py", line 230, in glCheckError
    raise self._errorClass(
OpenGL.error.GLError: GLError(
        err = 1282,
        description = b'\xed\xe5\xe4\xee\xef\xf3\xf1\xf2\xe8\xec\xe0\xff \xee\xef\xe5\xf0\xe0\xf6\xe8\xff',
        baseOperation = glLightModelfv,
        pyArgs = (
                GL_LIGHT_MODEL_AMBIENT,
                array([0., 0., 0., 1.], dtype=float32),
        ),
        cArgs = (
                GL_LIGHT_MODEL_AMBIENT,
                array([0., 0., 0., 1.], dtype=float32),
        ),
        cArguments = (
                GL_LIGHT_MODEL_AMBIENT,
                array([0., 0., 0., 1.], dtype=float32),
        )
)
PS C:\MH> .\.env\Scripts\python.exe -m pip list
Package    Version
---------- -------
numpy      1.21.0
pip        21.1.3
PyOpenGL   3.1.5
PyQt5      5.15.4
PyQt5-Qt5  5.15.2
PyQt5-sip  12.9.0
setuptools 56.0.0
PS C:\MH> python --version
Python 3.9.6
PS C:\MH>
```

**Comment by rwbaer** [comment]
Closing as it is graphics card specific and we have moved on to MH 1.2.0.  Reopen if it remains critical.
