### ISSUE TITLE
SyntaxError: invalid syntax in lib/glmodule.py (Ubuntu 22.04.2)

### ISSUE THREAD

**Issue by Absolute7070** [makehumancommunity/makehuman#232]
Got following output when running makehuman.py:

Traceback (most recent call last):
  File "makehuman.py", line 621, in <module>
    main()
  File "makehuman.py", line 611, in main
    from mhmain import MHApplication
  File "./core/mhmain.py", line 44, in <module>
    import mh
  File "./lib/mh.py", line 43, in <module>
    from glmodule import grabScreen, hasRenderSkin, renderSkin, getPickedColor, hasRenderToRenderbuffer, renderToBuffer, renderAlphaMask
  File "./lib/glmodule.py", line 76
    log.error(f"{func.__name__} raised {error}")
                                              ^
SyntaxError: invalid syntax

What is the syntax error in this part?

**Comment by Aranuvir** [comment]
There was obviously a fix some time ago.
