### ISSUE TITLE
Downloaded community model not saved properly

### ISSUE THREAD

**Issue by Fak3** [makehumancommunity/makehuman#26]
version: git master

I have downloaded community model "Angelina Jolie", then saved it, and loaded again. I noticed that eyes was changed (from ghostly white to default brown)
In the log there are bunch of errors:
```
Unknown modifier specified in MHM file: custom/Angelina's_lips
Background file Angelina profile.jpeg not found
Background file Angelina Jolie straight.jpeg not found
Failed to load material from file eyes/materials/diffuse_hazel.mhmat.
Problem loading binary mesh: ('compiled file missing: %s', '/home/u1/Documents/makehuman/v1py3/data/teeth/Mind_Teeth_01/mind_teeth_01.npz')
Problem loading binary proxy: ('compiled proxy file missing: %s', '/home/u1/Documents/makehuman/v1py3/data/teeth/Star_teeth/star_teeth.mhpxy')
Problem loading binary mesh: ('compiled file missing: %s', '/home/u1/Documents/makehuman/v1py3/data/teeth/Star_teeth/star_teeth.npz')
Problem loading binary proxy: ('compiled proxy file missing: %s', '/home/u1/Documents/makehuman/v1py3/data/teeth/Star_teeth_tri_with_litsphere/star_teeth_tri.mhpxy')
Problem loading binary mesh: ('compiled file missing: %s', '/home/u1/Documents/makehuman/v1py3/data/teeth/Star_teeth_tri_with_litsphere/star_teeth_tri.npz')
Cannot get texture for file path lit_teeth_gray.PNG, no such file.
Exception during event onFileSelected
Traceback (most recent call last):
  File "./core/events3d.py", line 211, in callEvent
    method(event)
  File "./apps/gui/guisave.py", line 267, in onFileSelected
    saveMHM(path)
  File "./apps/gui/guisave.py", line 72, in saveMHM
    G.app.selectedHuman.save(path)
  File "./apps/human.py", line 1627, in save
    handler(self, f)
  File "/home/z/pproj/makehuman/makehuman/plugins/3_libraries_material_chooser.py", line 318, in saveHandler
    materialPath = self.getRelativeMaterialPath(eyesObj.material.filename, proxy.file)
  File "/home/z/pproj/makehuman/makehuman/plugins/3_libraries_material_chooser.py", line 283, in getRelativeMaterialPath
    return getpath.getJailedPath(filepath, searchPaths)
  File "./lib/getpath.py", line 407, in getJailedPath
    if _withinJail(filepath):
  File "./lib/getpath.py", line 403, in _withinJail
    if isSubPath(path, j):
  File "./lib/getpath.py", line 254, in isSubPath
    subpath = canonicalPath(subpath)
  File "./lib/getpath.py", line 117, in canonicalPath
    return formatPath(os.path.realpath(path))
  File "/usr/lib64/python3.6/posixpath.py", line 387, in realpath
    filename = os.fspath(filename)
TypeError: expected str, bytes or os.PathLike object, not NoneType
./shared/animation.py:467: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  data[bonesList] = pose2.getAtFramePos(0, noBake=True)[[bonesList]]

Problem loading binary proxy: ('compiled proxy file missing: %s', '/home/u1/Documents/makehuman/v1py3/data/teeth/Mind_Teeth_01/mind_teeth_01.mhpxy')
```

**Comment by Aranuvir** [comment]
The basic problem here: a custom model file is missing a custom eye material. That's the reason for the "ghost" eyes. Perhaps we should consider to load a default material in that case. At least saving such a model with missing materials should not lead to an exception. Providing a fix for the exception. Thorough testing is needed...

**Comment by Aranuvir** [comment]
Since a3 is out this can be closed?
