### ISSUE TITLE
openGL error : gl.draw 

### ISSUE THREAD

**Issue by LuxusIX** [makehumancommunity/makehuman#260]
i use  Arch Linux x86_64 in a Lenovo 81VT IdeaPad 1 11IGL05 with a CPU: Intel Celeron N4020 (2) @ 2.800GHz  and a GPU: Intel GeminiLake [UHD Graphics 600] 
All composant are up to date 
i use the makehumain version 1.3.0 and i have this error:

the windows open and all UI elements but the modele doesn't appear and at the bottom, it's wrote :
`an error occured. Check Utilities/logs for more Information! Error Message: gl.draw`
but i executed in terminal  and i had that:
`libpng warning: iCCP: known incorrect sRGB profile
gl.reshape
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/OpenGL/latebind.py", line 43, in __call__
    return self._finalCall( *args, **named )
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/makehuman/lib/glmodule.py", line 243, in reshape
    updatePickingBuffer()
  File "/opt/makehuman/lib/glmodule.py", line 155, in updatePickingBuffer
    drawMeshes(True)
  File "/opt/makehuman/lib/glmodule.py", line 1041, in drawMeshes
    drawOrPick(pickMode, obj)
  File "/opt/makehuman/lib/glmodule.py", line 681, in drawOrPick
    obj.pick()
  File "/opt/makehuman/lib/object3d.py", line 290, in pick
    return glmodule.pickMesh(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/makehuman/lib/glmodule.py", line 652, in pickMesh
    glVertexPointer(3, GL_FLOAT, 0, obj.verts)
  File "/usr/lib/python3.12/site-packages/OpenGL/latebind.py", line 47, in __call__
    return self._finalCall( *args, **named )
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/OpenGL/wrapper.py", line 818, in wrapperCall
    storeValues(
  File "/usr/lib/python3.12/site-packages/OpenGL/arrays/arrayhelpers.py", line 156, in __call__
    contextdata.setValue( self.constant, pyArgs[self.pointerIndex] )
  File "/usr/lib/python3.12/site-packages/OpenGL/contextdata.py", line 58, in setValue
    context = getContext( context )
              ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/OpenGL/contextdata.py", line 40, in getContext
    raise error.Error(
OpenGL.error.Error: Attempt to retrieve context when no valid context
gl.draw
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/OpenGL/latebind.py", line 43, in __call__
    return self._finalCall( *args, **named )
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/makehuman/lib/glmodule.py", line 1053, in draw
    _draw(productionRender)
  File "/opt/makehuman/lib/glmodule.py", line 1045, in _draw
    drawMeshes(False, productionRender)
  File "/opt/makehuman/lib/glmodule.py", line 1041, in drawMeshes
    drawOrPick(pickMode, obj)
  File "/opt/makehuman/lib/glmodule.py", line 684, in drawOrPick
    obj.draw()
  File "/opt/makehuman/lib/object3d.py", line 286, in draw
    return glmodule.drawMesh(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/makehuman/lib/glmodule.py", line 477, in drawMesh
    glTexCoordPointer(2, GL_FLOAT, 0, obj.UVs)
  File "/usr/lib/python3.12/site-packages/OpenGL/latebind.py", line 47, in __call__
    return self._finalCall( *args, **named )
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/OpenGL/wrapper.py", line 818, in wrapperCall
    storeValues(
  File "/usr/lib/python3.12/site-packages/OpenGL/arrays/arrayhelpers.py", line 156, in __call__
    contextdata.setValue( self.constant, pyArgs[self.pointerIndex] )
  File "/usr/lib/python3.12/site-packages/OpenGL/contextdata.py", line 58, in setValue
    context = getContext( context )
              ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/OpenGL/contextdata.py", line 40, in getContext
    raise error.Error(
OpenGL.error.Error: Attempt to retrieve context when no valid context
gl.reshape
Traceback (most recent call last):
  File "/opt/makehuman/lib/glmodule.py", line 243, in reshape
    updatePickingBuffer()
  File "/opt/makehuman/lib/glmodule.py", line 155, in updatePickingBuffer
    drawMeshes(True)
  File "/opt/makehuman/lib/glmodule.py", line 1041, in drawMeshes
    drawOrPick(pickMode, obj)
  File "/opt/makehuman/lib/glmodule.py", line 681, in drawOrPick
    obj.pick()
  File "/opt/makehuman/lib/object3d.py", line 290, in pick
    return glmodule.pickMesh(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/makehuman/lib/glmodule.py", line 652, in pickMesh
    glVertexPointer(3, GL_FLOAT, 0, obj.verts)
  File "/usr/lib/python3.12/site-packages/OpenGL/latebind.py", line 43, in __call__
    return self._finalCall( *args, **named )
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/OpenGL/wrapper.py", line 818, in wrapperCall
    storeValues(
  File "/usr/lib/python3.12/site-packages/OpenGL/arrays/arrayhelpers.py", line 156, in __call__
    contextdata.setValue( self.constant, pyArgs[self.pointerIndex] )
  File "/usr/lib/python3.12/site-packages/OpenGL/contextdata.py", line 58, in setValue
    context = getContext( context )
              ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/OpenGL/contextdata.py", line 40, in getContext
    raise error.Error(
OpenGL.error.Error: Attempt to retrieve context when no valid context
gl.draw
Traceback (most recent call last):
  File "/opt/makehuman/lib/glmodule.py", line 1053, in draw
    _draw(productionRender)
  File "/opt/makehuman/lib/glmodule.py", line 1045, in _draw
    drawMeshes(False, productionRender)
  File "/opt/makehuman/lib/glmodule.py", line 1041, in drawMeshes
    drawOrPick(pickMode, obj)
  File "/opt/makehuman/lib/glmodule.py", line 684, in drawOrPick
    obj.draw()
  File "/opt/makehuman/lib/object3d.py", line 286, in draw
    return glmodule.drawMesh(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/makehuman/lib/glmodule.py", line 477, in drawMesh
    glTexCoordPointer(2, GL_FLOAT, 0, obj.UVs)
  File "/usr/lib/python3.12/site-packages/OpenGL/latebind.py", line 43, in __call__
    return self._finalCall( *args, **named )
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/OpenGL/wrapper.py", line 818, in wrapperCall
    storeValues(
  File "/usr/lib/python3.12/site-packages/OpenGL/arrays/arrayhelpers.py", line 156, in __call__
    contextdata.setValue( self.constant, pyArgs[self.pointerIndex] )
  File "/usr/lib/python3.12/site-packages/OpenGL/contextdata.py", line 58, in setValue
    context = getContext( context )
              ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/OpenGL/contextdata.py", line 40, in getContext
    raise error.Error(
OpenGL.error.Error: Attempt to retrieve context when no valid context
gl.draw
Traceback (most recent call last):
  File "/opt/makehuman/lib/glmodule.py", line 1053, in draw
    _draw(productionRender)
  File "/opt/makehuman/lib/glmodule.py", line 1045, in _draw
    drawMeshes(False, productionRender)
  File "/opt/makehuman/lib/glmodule.py", line 1041, in drawMeshes
    drawOrPick(pickMode, obj)
  File "/opt/makehuman/lib/glmodule.py", line 684, in drawOrPick
    obj.draw()
  File "/opt/makehuman/lib/object3d.py", line 286, in draw
    return glmodule.drawMesh(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/makehuman/lib/glmodule.py", line 477, in drawMesh
    glTexCoordPointer(2, GL_FLOAT, 0, obj.UVs)
  File "/usr/lib/python3.12/site-packages/OpenGL/latebind.py", line 43, in __call__
    return self._finalCall( *args, **named )
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/OpenGL/wrapper.py", line 818, in wrapperCall
    storeValues(
  File "/usr/lib/python3.12/site-packages/OpenGL/arrays/arrayhelpers.py", line 156, in __call__
    contextdata.setValue( self.constant, pyArgs[self.pointerIndex] )
  File "/usr/lib/python3.12/site-packages/OpenGL/contextdata.py", line 58, in setValue
    context = getContext( context )
              ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/OpenGL/contextdata.py", line 40, in getContext
    raise error.Error(
OpenGL.error.Error: Attempt to retrieve context when no valid context

`

**Comment by Vidyut** [comment]
I have this problem too on Ubundu 24.04 with an Nvidia card. I use MPFB2 and for a long time have been curious about MakeHuman that started it all. But unfortunately, I've never been able to run it on my machine.

I'm planning to upgrade to 24.10 which supports a new NVIDIA driver on the off chance the opengl issue goes away...

**Comment by joepal1976** [comment]
I doubt it will help. The likelihood actually decreases over time, as newer graphics drivers drop support for ancient standards which are no longer relevant. 

This FAQ item might be relevant: https://static.makehumancommunity.org/makehuman/faq/current_status.html

Nvidia cards have mostly worked until now. Intel cards started having problems several years ago.

**Comment by Vidyut** [comment]
Ah dang. That explains the relatively small community for such a fantastic software. Truly feels like something historic is slipping out of our hands. I wish I had been able to load it at least once to see what the fuss was about. Or I wish I were a coder and could move everything to newer drivers. :(

**Comment by Vidyut** [comment]
Out of curiosity, this part where the application still works for most platforms and will continue to work... can it be updated with what version of OpenGL is still supported by these machines? Just to see if maybe we can install an older driver or scrounge up and old laptop that has it specifically... Damn. I donated two old laptops a few years ago. Now I wish I'd kept them. They were too old to be too useful to the students I donated them to, but I bet they'd run Makehuman.

**Comment by joepal1976** [comment]
It's hard to say. But since you run nvidia: I can launch makehuman on ubuntu 24.04 with an RTX 4060 as main card, and nvidia drivers 550:

```
joepal@hasur:~$ dpkg -l | grep -i nvidia-driver
ii  nvidia-driver-550                                        550.120-0ubuntu0.24.04.1                    amd64        NVIDIA driver metapackage
```

I would have assumed that any nvidia card running with nvidia-driver would be able to launch makehuman, at least from source.

Running with the noveau driver is a different thing though.

**Comment by LuxusIX** [comment]
I resolved it
The problem was Wayland, specially xorg-xwayland
All details are [here](https://github.com/LuxusIX/Resolve_gl.draw_error_in_MakeHuman_in_linux_distro)


Any way, to resolve it , you need to move your desktop environment on X11
That's how I resolved it!

**Comment by joepal1976** [comment]
Thanks, that's really helpful.

**Comment by Vidyut** [comment]
This is the one thing I hadn't thought of trying, even as I'd run into and solved other problems with Wayland and NVIDIA. Facepalm. Thanks a ton for posting your solution.

**Comment by Vidyut** [comment]
Update. I fiddled around a bit more with this with this new insight and adding this before running makehuman works in Wayland as well. This should probably be added to the startup file.

`export PYOPENGL_PLATFORM='glx'`

Just got it working, but am unfortunately very busy with other things in the coming days so any extensive use/testing will have to wait, but not run into further errors so far. Stuff seems to "just work" now.

Terminal has stopped complaining about opengl altogether.
