### ISSUE TITLE
Makehuman don't work with optirun (Nvidia Optimus Linux)

### ISSUE THREAD

**Issue by FabriceSalvaire** [makehumancommunity/makehuman#47]
But not sure it is due to Makehuman. I believe I ran a Qt 5 QWidget  project with optirun in the past.

```
Exception during event onStart
Traceback (most recent call last):
  File "./core/events3d.py", line 211, in callEvent
    method(event)
  File "./core/mhmain.py", line 848, in onStart
    self.startupSequence()
  File "./core/mhmain.py", line 813, in startupSequence
    ( not mh.Shader.supported() or mh.Shader.glslVersion() < (1,20) ):
  File "./lib/shader.py", line 292, in glslVersion
    cls._glsl_version_str = str(cls._glsl_version_str, encoding='utf-8')
TypeError: decoding to str: need a bytes-like object, NoneType found
Exception during event onMouseMovedCallback
Traceback (most recent call last):
  File "/opt/python-virtual-env/py37/lib/python3.7/site-packages/OpenGL/latebind.py", line 41, in __call__
    return self._finalCall( *args, **named )
TypeError: 'NoneType' object is not callable
```

**Comment by FabriceSalvaire** [comment]
it works with primusrun, there is just glitches when we move the mouse hover the viewport.

**Comment by joepal1976** [comment]
Can you check if current master solves the problem?
