### ISSUE TITLE
Importing .mhx2 with clothing does not import in Blender release candidate 2.

### ISSUE THREAD

**Issue by jedidorn** [makehumancommunity/makehuman#53]
When importing a model that is clothed using the clothes avalaible in MH does not import in Blender 2.8 release candidate 2. An error is displayed mentioning importer.py.

There is no problem when importing to blender when the model has no clothing.

I have tried several of the available "standaard clothing".
The version of MH is the latest test version.

I did re-install Blender and MH but problem is still there.

**Comment by Aranuvir** [comment]
With the latest build from July 20 ~23:00 I do not have any problems.
Sorry, but that's the wrong bug tracker. 

MHX2 is hosted here (with some glitches):
https://bitbucket.org/Diffeomorphic/mhx2-makehuman-exchange/src/default/

or better here (you must be logged in (!) to see the repo, not knowing why):
https://bitbucket.org/Aranuvir/mhx2-makehuman-exchange/src/default/

Closing this topic, due to wrong bug tracker.

**Comment by balamut152** [comment]
when I export model without clothes addon work. But if I add clothes I have error:
Creating CYCLES material Ann2:Female_sportsuit01.obj:Female_sportsuit01
Traceback (most recent call last):
  File "/home/balamut/.config/blender/2.80/scripts/addons/import_runtime_mhx2/importer.py", line 56, in execute
    importMhx2File(self.filepath, cfg, context)
  File "/home/balamut/.config/blender/2.80/scripts/addons/import_runtime_mhx2/importer.py", line 144, in importMhx2File
    build(struct, cfg, context)
  File "/home/balamut/.config/blender/2.80/scripts/addons/import_runtime_mhx2/importer.py", line 201, in build
    mname,mat = buildMaterial(mhMaterial, scn, cfg)
  File "/home/balamut/.config/blender/2.80/scripts/addons/import_runtime_mhx2/materials.py", line 40, in buildMaterial
    buildMaterialCycles(mat, mhMaterial, scn, cfg)
  File "/home/balamut/.config/blender/2.80/scripts/addons/import_runtime_mhx2/materials.py", line 159, in buildMaterialCycles
    normalTex.color_space = 'NONE'
AttributeError: 'ShaderNodeTexImage' object has no attribute 'color_space'
