### ISSUE TITLE
Program doesn´t start, stops at "loading human"

### ISSUE THREAD

**Issue by Reiner2019** [makehumancommunity/makehuman#56]
HI,
I installed makehuman 1.2.a3 on my Windows 10 Computer. I can´t run it because it stops at opening. The logfile says: 

[2019-08-25 09:33:34,678] log.py->message():118 -- MESSAGE -- Initialized logging
[2019-08-25 09:33:34,685] log.py->debug():97 -- DEBUG -- VERSION: 1.2.0 Alpha3
[2019-08-25 09:33:34,685] log.py->debug():97 -- DEBUG -- HG REVISION: UNKNOWN
[2019-08-25 09:33:34,685] log.py->debug():97 -- DEBUG -- SHORT VERSION: alpha3
[2019-08-25 09:33:34,685] log.py->debug():97 -- DEBUG -- BASEMESH VERSION: hm08
[2019-08-25 09:33:34,685] log.py->debug():97 -- DEBUG -- IS BUILT (FROZEN): No
[2019-08-25 09:33:34,685] log.py->debug():97 -- DEBUG -- IS RELEASE VERSION: Yes
[2019-08-25 09:33:34,685] log.py->debug():97 -- DEBUG -- DEFAULT ENCODING: utf-8
[2019-08-25 09:33:34,685] log.py->debug():97 -- DEBUG -- FILESYSTEM ENCODING: utf-8
[2019-08-25 09:33:34,685] log.py->debug():97 -- DEBUG -- STDOUT ENCODING: cp1252
[2019-08-25 09:33:34,685] log.py->debug():97 -- DEBUG -- LOCALE PREFERRED ENCODING: cp1252
[2019-08-25 09:33:34,685] log.py->debug():97 -- DEBUG -- WORKING DIRECTORY: C:\Program Files (x86)\makehuman-community\makehuman
[2019-08-25 09:33:34,685] log.py->debug():97 -- DEBUG -- HOME LOCATION: C:/Users/zapata/Documents
[2019-08-25 09:33:34,685] log.py->debug():97 -- DEBUG -- PYTHON PATH: ./;./lib;./apps;./shared;./apps/gui;./core;C:\Program Files (x86)\makehuman-community\Python\python36.zip;C:\Program Files (x86)\makehuman-community\Python;C:\Program Files (x86)\makehuman-community\pkgs
[2019-08-25 09:33:34,685] log.py->debug():97 -- DEBUG -- DLL PATH: C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Users\zapata\AppData\Local\Microsoft\WindowsApps;
[2019-08-25 09:33:34,685] log.py->debug():97 -- DEBUG -- SYS.VERSION: 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 16:07:46) [MSC v.1900 32 bit (Intel)]
[2019-08-25 09:33:34,685] log.py->debug():97 -- DEBUG -- SYS.PLATFORM: win32
[2019-08-25 09:33:34,690] log.py->debug():97 -- DEBUG -- SYS.EXECUTABLE: C:\Program Files (x86)\makehuman-community\Python\pythonw.exe
[2019-08-25 09:33:34,690] log.py->debug():97 -- DEBUG -- PLATFORM.MACHINE: AMD64
[2019-08-25 09:33:34,691] log.py->debug():97 -- DEBUG -- PLATFORM.PROCESSOR: Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
[2019-08-25 09:33:34,691] log.py->debug():97 -- DEBUG -- PLATFORM.UNAME.RELEASE: 10
[2019-08-25 09:33:34,691] log.py->debug():97 -- DEBUG -- PLATFORM.WIN32_VER: 10 10.0.17134 SP0 Multiprocessor Free
[2019-08-25 09:33:34,814] log.py->debug():97 -- DEBUG -- NUMPY.VERSION: 1.13.3
[2019-08-25 09:33:34,849] acceleratesupport.py-><module>():17 -- MESSAGE -- No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
[2019-08-25 09:33:35,328] log.py->debug():97 -- DEBUG -- QT.VERSION: 5.10.1
[2019-08-25 09:33:35,334] log.py->debug():97 -- DEBUG -- QT.JPG_SUPPORT: not supported
[2019-08-25 09:33:35,334] log.py->debug():97 -- DEBUG -- QT.SVG_SUPPORT: not supported
[2019-08-25 09:33:35,334] log.py->debug():97 -- DEBUG -- QT.PLUGIN_PATH: C:/Program Files (x86)/makehuman-community/pkgs/PyQt5/Qt/plugins;C:/Program Files (x86)/makehuman-community/Python
[2019-08-25 09:33:35,334] log.py->debug():97 -- DEBUG -- QT.PLUGIN_PATH_ENV: 
[2019-08-25 09:33:35,334] log.py->debug():97 -- DEBUG -- QT.CONF: NOT PRESENT
[2019-08-25 09:33:35,666] log.py->debug():97 -- DEBUG -- PYOPENGL.VERSION: 3.1.0
[2019-08-25 09:33:35,667] log.py->debug():97 -- DEBUG -- GL.VENDOR: Intel
[2019-08-25 09:33:35,667] log.py->debug():97 -- DEBUG -- GL.RENDERER: Intel(R) UHD Graphics 620
[2019-08-25 09:33:35,667] log.py->debug():97 -- DEBUG -- GL.VERSION: 4.5.0 - Build 23.20.16.4973
[2019-08-25 09:33:35,669] log.py->debug():97 -- DEBUG -- 4.50 - Build 23.20.16.4973
[2019-08-25 09:33:35,669] log.py->debug():97 -- DEBUG -- GLSL.VERSION: 4.50 - Build 23.20.16.4973
[2019-08-25 09:33:35,672] log.py->debug():97 -- DEBUG -- GL.EXTENSION: GL_ARB_multisample enabled (4x samples)
[2019-08-25 09:33:35,678] log.py->debug():97 -- DEBUG -- Creating new texture for image data/textures/texture_notfound.png.
[2019-08-25 09:33:35,683] log.py->debug():97 -- DEBUG -- GL.EXTENSION: GL_ARB_texture_non_power_of_two enabled
[2019-08-25 09:33:35,759] log.py->debug():97 -- DEBUG -- initTexture: 256, 256, False
[2019-08-25 09:33:35,911] log.py->debug():97 -- DEBUG -- Setting language to english
[2019-08-25 09:33:35,912] log.py->warning():104 -- WARNING -- No settings file found, starting with default settings.
[2019-08-25 09:33:35,912] log.py->warning():104 -- WARNING -- Incompatible MakeHuman settings (version undefined) detected (expected 1.2.0). Loading default settings.
[2019-08-25 09:33:35,912] log.py->debug():97 -- DEBUG -- Setting language to english
[2019-08-25 09:33:35,913] log.py->warning():104 -- WARNING -- shortcuts.ini out of date; ignoring
[2019-08-25 09:33:35,913] log.py->message():118 -- MESSAGE -- Initializing default theme first.
[2019-08-25 09:33:35,913] log.py->message():118 -- MESSAGE -- Theme default version 1.1.0
[2019-08-25 09:33:35,914] log.py->debug():97 -- DEBUG -- Loaded theme data/themes/default.mht
[2019-08-25 09:33:35,914] log.py->debug():97 -- DEBUG -- Using Qt system style windowsvista
[2019-08-25 09:33:36,801] log.py->message():118 -- MESSAGE -- Loading human
[2019-08-25 09:33:36,803] log.py->debug():97 -- DEBUG -- Loading binary mesh data/3dobjs/base.npz.
[2019-08-25 09:33:36,808] log.py->debug():97 -- DEBUG -- NPZ-File: maxmimum number of faces for one vertex: 5
[2019-08-25 09:33:36,874] log.py->debug():97 -- DEBUG -- Loading material from file data/skins/default.mhmat
[2019-08-25 09:33:36,922] log.py->warning():104 -- WARNING -- Exception during event onStart
Traceback (most recent call last):
  File "./core\events3d.py", line 211, in callEvent
    method(event)
  File "./core\mhmain.py", line 848, in onStart
    self.startupSequence()
  File "./core\mhmain.py", line 772, in startupSequence
    self.loadHuman()
  File "./core\mhmain.py", line 409, in loadHuman
    self.selectedHuman = self.addObject(human.Human(files3d.loadMesh(mh.getSysDataPath("3dobjs/base.obj"), maxFaces = 5)))
  File "./apps\human.py", line 88, in __init__
    self.material = material.fromFile(getSysDataPath('skins/default.mhmat'))
  File "./shared\material.py", line 1408, in fromFile
    mat.fromFile(filename)
  File "./shared\material.py", line 488, in fromFile
    self.configureShading(diffuse=shaderConfig_diffuse, bump=shaderConfig_bump, normal=shaderConfig_normal, displacement=shaderConfig_displacement, spec=shaderConfig_spec, vertexColors=shaderConfig_vertexColors, transparency=shaderConfig_transparency, ambientOcclusion=shaderConfig_ambientOcclusion)
  File "./shared\material.py", line 949, in configureShading
    self._updateShaderConfig()
  File "./shared\material.py", line 986, in _updateShaderConfig
    bump = self._shaderConfig['bump'] and self.supportsBump()
  File "./shared\material.py", line 881, in supportsBump
    if self.shaderObj and result:
  File "./shared\material.py", line 1046, in shaderObj
    return self.getShaderObj()
  File "./shared\material.py", line 1042, in getShaderObj
    return shader.getShader(shaderPath, self.shaderDefines)
  File "./lib\shader.py", line 529, in getShader
    shader = Shader(path, defines)
  File "./lib\shader.py", line 319, in __init__
    self.initShader()
  File "./lib\shader.py", line 446, in initShader
    self.updateUniforms()
  File "./lib\shader.py", line 469, in updateUniforms
    for uniform in self.getUniforms():
  File "./lib\shader.py", line 459, in getUniforms
    uniform = VectorUniform(self.shaderId, index, name, type)
  File "./lib\shader.py", line 123, in __init__
    super(VectorUniform, self).__init__(pgm, index, name, pytype, dims)
  File "./lib\shader.py", line 60, in __init__
    self.location = glGetUniformLocation(self.pgm, name)
  File "C:\Program Files (x86)\makehuman-community\pkgs\OpenGL\latebind.py", line 61, in __call__
    return self.wrapperFunction( self.baseFunction, *args, **named )
  File "C:\Program Files (x86)\makehuman-community\pkgs\OpenGL\GL\VERSION\GL_2_0.py", line 383, in glGetUniformLocation
    raise ValueError( """Non-null name required""" )
ValueError: Non-null name required

My Graphics Card is Intel UHD Graphics 620

I would be happy about help on this issue and hope that the graphics card isn´t incompatible.

**Comment by joepal1976** [comment]
This isn't a fix, but can you check if makehuman starts if you run with --noshaders?

http://www.makehumancommunity.org/wiki/FAQ:MakeHuman_renders_odd_colours_and_weird_transparency_artefacts._Can_you_help_me%3F

**Comment by Reiner2019** [comment]
Thank you, I will try this. On the Intel site I read that this graphics card supports OpenGL up to version 4.5 . So maybe I should look for a driver for a higher Version. Sorry for my wild guesses, I have no knowledge about hardware/software ingeneering, just fantasy...

**Comment by Reiner2019** [comment]
HI, thanks again for your help. However it doesn´t work. My shortcut properties (I have put the shortcut on my desktop) say 

target location: Pyton

target: 
"C:\Program Files (x86)\makehuman-community\Python\pythonw.exe" "C:\Program Files (x86)\makehuman-community\mhstartwrapper.py"

execute in:   %HOMEDRIVE%\%HOMEPATH%

I tried to put -noshader in different combinations with the target name:
"C:\Program Files (x86)\makehuman-community\Python\pythonw.exe" **-noshaders** "C:\Program Files (x86)\makehuman-community\mhstartwrapper.py"

"C:\Program Files (x86)\makehuman-community\Python\pythonw.exe" "C:\Program Files (x86)\makehuman-community\mhstartwrapper.py" **-noshaders**

"C:\Program Files (x86)\makehuman-community\Python\pythonw.exe" -noshaders

None of these versions works.

**Comment by joepal1976** [comment]
Ok. I have no good answer right now. Looking at the code, it seems strange that a null name gets that far.

**Comment by josedanielr** [comment]
Hi, @joepal1976 for me launching it as `python makehuman.py --noshaders` does work. What can be done about it?

**Comment by Vecol** [comment]
Got same issue running from source and find out the [name](https://github.com/makehumancommunity/makehuman/blob/c00a5302deb7a7116466f4fbb5072899b09bdaa4/makehuman/lib/shader.py#L461)  here could be empty.Remove the empty names, everything is fine.

**Comment by Aranuvir** [comment]
The problem most likely goes slightly beyond removing some empty name. IMHO an empty name indicates some missing OpenGl functions and OpenGl doesn't work correctly at all.

**Comment by Vecol** [comment]
Yeah, the empty names should be "gl_" stuffs, glGetActiveUniform seems not working correctly in some case.

**Comment by Aranuvir** [comment]
Well filtering out that stuff probably doesn't cost that much and in worst case we get something similar to a noshaders effect. (commit: bf4cf8c)
BTW, what does it mean everything is fine? Do you get correct transparency e.g.for the eyebrows/eyelashes?

**Comment by Vecol** [comment]
Looks fine to me.
![face2](https://user-images.githubusercontent.com/13953965/75666628-1a64c580-5cb1-11ea-9fac-33d9e5cb6e5d.png)
![face3](https://user-images.githubusercontent.com/13953965/75666642-1f297980-5cb1-11ea-861a-73e2e8ddaf43.png)

**Comment by Aranuvir** [comment]
Great, looking good so far. Did you test with the latest commit which should ignore empty names?

**Comment by 007roy** [comment]
If I right click, run with graphics processor -> High performance NVIDIA processor as apposed to the default using integrated graphics it launches fine.

**Comment by Aranuvir** [comment]
That was fixed.
