### ISSUE TITLE
Makehuman utilites in Master 1.2.0 Alpha4 (master:0e683a42) malfunction on Windows

### ISSUE THREAD

**Issue by rwbaer** [makehumancommunity/makehuman#71]
I just dowloaded a fresh copy of master 1.2.0 Alpha4 (master:0e683a42) and tried to run the various utility helpers for developers.  There seemed to be import problems with each.  Have there be refactorings that mean we need to upgrade import statements.  Am I doing something wrong?

Here is the effect of running in Pycharm:

```
E:\Anaconda3\envs\pip\python.exe C:/Users/rbaer/PycharmProjects/makehuman/makehuman/compile_proxies.py
Traceback (most recent call last):
  File "C:/Users/rbaer/PycharmProjects/makehuman/makehuman/compile_proxies.py", line 44, in <module>
    import proxy
ModuleNotFoundError: No module named 'proxy'

Process finished with exit code 1


E:\Anaconda3\envs\pip\python.exe C:/Users/rbaer/PycharmProjects/makehuman/makehuman/compile_proxies.py
Traceback (most recent call last):
  File "C:/Users/rbaer/PycharmProjects/makehuman/makehuman/compile_proxies.py", line 44, in <module>
    import proxy
ModuleNotFoundError: No module named 'proxy'

Process finished with exit code 1


E:\Anaconda3\envs\pip\python.exe C:/Users/rbaer/PycharmProjects/makehuman/makehuman/compile_targets.py
Traceback (most recent call last):
  File "C:/Users/rbaer/PycharmProjects/makehuman/makehuman/compile_targets.py", line 42, in <module>
    import algos3d
ModuleNotFoundError: No module named 'algos3d'

Process finished with exit code 1


E:\Anaconda3\envs\pip\python.exe C:/Users/rbaer/PycharmProjects/makehuman/makehuman/create_pylint_log.py
The command line is too long.

Process finished with exit code 0


E:\Anaconda3\envs\pip\python.exe C:/Users/rbaer/PycharmProjects/makehuman/makehuman/download_assets_git.py
Traceback (most recent call last):
  File "C:/Users/rbaer/PycharmProjects/makehuman/makehuman/download_assets_git.py", line 55, in <module>
    import getpath
ModuleNotFoundError: No module named 'getpath'

Process finished with exit code 1



```

**Comment by joepal1976** [comment]
I think you have to cd to the makehuman directory and run the scripts from there. The python path likely adds relative pathnames (such as "./apps") for importing.

**Comment by Aranuvir** [comment]
I did not have any problems with these tools. Indeed they should be invoked from inside the makehuman folder.
Suggesting to close the topic.

**Comment by Aranuvir** [comment]
There hasn't been any update. Closing.
