### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by xinminsu** [makehumancommunity/makehuman#82]
(makehuman) C:\makehuman\makehuman>python makehuman.py
MakeHuman Copyright (C) 2001-2018 http://www.makehumancommunity.org
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions. For details use the option --license

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\makehuman\lib\site-packages\OpenGL\latebind.py", line 43, in __call__
    return self._finalCall( *args, **named )
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./lib\qtui.py", line 295, in initializeGL
    gl.OnInit()
  File "./lib\glmodule.py", line 316, in OnInit
    glLightModelfv(GL_LIGHT_MODEL_AMBIENT, A(0.0, 0.0, 0.0, 1.0))
  File "C:\ProgramData\Anaconda3\envs\makehuman\lib\site-packages\OpenGL\latebind.py", line 47, in __call__
    return self._finalCall( *args, **named )
  File "C:\ProgramData\Anaconda3\envs\makehuman\lib\site-packages\OpenGL\wrapper.py", line 700, in wrapperCall
    raise err
  File "C:\ProgramData\Anaconda3\envs\makehuman\lib\site-packages\OpenGL\wrapper.py", line 693, in wrapperCall
    result = wrappedOperation( *cArguments )
  File "C:\ProgramData\Anaconda3\envs\makehuman\lib\site-packages\OpenGL\platform\baseplatform.py", line 415, in __call__
    return self( *args, **named )
  File "C:\ProgramData\Anaconda3\envs\makehuman\lib\site-packages\OpenGL\error.py", line 234, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
        err = 1282,
        description = b'\xce\xde\xd0\xa7\xb2\xd9\xd7\xf7',
        baseOperation = glLightModelfv,
        pyArgs = (
                GL_LIGHT_MODEL_AMBIENT,
                array([0., 0., 0., 1.], dtype=float32),
        ),
        cArgs = (
                GL_LIGHT_MODEL_AMBIENT,
                array([0., 0., 0., 1.], dtype=float32),
        ),
        cArguments = (
                GL_LIGHT_MODEL_AMBIENT,
                array([0., 0., 0., 1.], dtype=float32),
        )
)

(makehuman) C:\makehuman\makehuman>

**Comment by xinminsu** [comment]
ok in other nvidia gpu computer.
