### ISSUE TITLE
Ubuntu  16.04 xenial: python error when I run it

### ISSUE THREAD

**Issue by catafest** [makehumancommunity/makehuman#84]
I got this error: 

```
SYS.VERSION: 3.5.2 (default, Oct  8 2019, 13:06:37)  [GCC 5.4.0 20160609]
SYS.PLATFORM: linux
SYS.EXECUTABLE: /usr/bin/python3
PLATFORM.MACHINE: x86_64
PLATFORM.PROCESSOR: x86_64
PLATFORM.UNAME.RELEASE: 4.15.0-88-generic
PLATFORM.LINUX_DISTRIBUTION: Ubuntu 16.04 xenial
NUMPY.VERSION: 1.17.3
Traceback (most recent call last):
  File "makehuman.py", line 613, in <module>
    main()
  File "makehuman.py", line 603, in main
    from mhmain import MHApplication
  File "./core/mhmain.py", line 45, in <module>
    import mh
  File "./lib/mh.py", line 43, in <module>
    from glmodule import grabScreen, hasRenderSkin, renderSkin, getPickedColor, hasRenderToRenderbuffer, renderToBuffer, renderAlphaMask
  File "./lib/glmodule.py", line 76
    log.error(f"{func.__name__} raised {error}")
                                              ^
SyntaxError: invalid syntax

```

**Comment by Aranuvir** [comment]
This string formatting syntax was introduced with Python 3.6 and isn't support with your OS-version. Since Xenial is one LTS behind and will be EOL in April, the bug gets a won't fix, sorry. 
We decided to test MakeHuman against Python 3.8.2, which will be the version of the next Ubuntu LTS release.
