### ISSUE TITLE
startup log:  openGL error 1286 on Mac - framebuffer

### ISSUE THREAD

**Issue by rwbaer** [makehumancommunity/makehuman#95]
Log errors on Mac that halted machine:
[2020-05-28 11:56:23,149] log.py->debug():97 -- DEBUG -- QT.PLUGIN_PATH_ENV: 
[2020-05-28 11:56:23,149] log.py->debug():97 -- DEBUG -- QT.CONF: NOT PRESENT
[2020-05-28 11:56:24,925] log.py->debug():97 -- DEBUG -- PYOPENGL.VERSION: 3.1.0
[2020-05-28 11:56:24,926] log.py->debug():97 -- DEBUG -- GL.VENDOR: NVIDIA Corporation
[2020-05-28 11:56:24,928] log.py->debug():97 -- DEBUG -- GL.RENDERER: NVIDIA GeForce GT 650M OpenGL Engine
[2020-05-28 11:56:24,929] log.py->debug():97 -- DEBUG -- GL.VERSION: 2.1 NVIDIA-14.0.32 355.11.11.10.10.143
[2020-05-28 11:56:24,932] log.py->debug():97 -- DEBUG -- 1.20
[2020-05-28 11:56:24,934] log.py->debug():97 -- DEBUG -- GLSL.VERSION: 1.20
[2020-05-28 11:56:24,943] log.py->debug():97 -- DEBUG -- GL.EXTENSION: GL_ARB_multisample enabled (4x samples)
[2020-05-28 11:56:24,953] log.py->debug():97 -- DEBUG -- Creating new texture for image data/textures/texture_notfound.png.
[2020-05-28 11:56:24,959] log.py->debug():97 -- DEBUG -- GL.EXTENSION: GL_ARB_texture_non_power_of_two enabled
[2020-05-28 11:56:24,999] log.py->debug():97 -- DEBUG -- initTexture: 256, 256, False
[2020-05-28 11:56:25,010] log.py->error():111 -- ERROR -- gl.reshape
Traceback (most recent call last):
  File "./lib/glmodule.py", line 243, in reshape
    updatePickingBuffer()
  File "./lib/glmodule.py", line 153, in updatePickingBuffer
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT)
  File "/Users/Rob/anaconda3/envs/pip/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 402, in __call__
    return self( *args, **named )
  File "/Users/Rob/anaconda3/envs/pip/lib/python3.7/site-packages/OpenGL/error.py", line 232, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
	err = 1286,
	description = b'invalid framebuffer operation',
	baseOperation = glClear,
	cArguments = (16640,)
)
[2020-05-28 11:56:25,054] log.py->error():111 -- ERROR -- gl.reshape
Traceback (most recent call last):
  File "./lib/glmodule.py", line 243, in reshape
    updatePickingBuffer()
  File "./lib/glmodule.py", line 153, in updatePickingBuffer
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT)
  File "/Users/Rob/anaconda3/envs/pip/lib/python3.7/site-packages/OpenGL/error.py", line 232, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
	err = 1286,
	description = b'invalid framebuffer operation',
	baseOperation = glClear,
	cArguments = (16640,)
)
[2020-05-28 11:56:25,114] log.py->debug():97 -- DEBUG -- Setting language to english
[2020-05-28 11:56:25,118] log.py->debug():97 -- DEBUG -- Setting language to english
[2020-05-28 11:56:25,127] log.py->message():118 -- MESSAGE -- Initializing default theme first.
[2020-05-28 11:56:25,130] log.py->message():118 -- MESSAGE -- Theme default version 1.1.0
[2020-05-28 11:56:25,131] log.py->debug():97 -- DEBUG -- Loaded theme data/themes/default.mht
[2020-05-28 11:56:25,131] log.py->debug():97 -- DEBUG -- Using Qt system style macintosh
[2020-05-28 11:56:25,702] log.py->message():118 -- MESSAGE -- Loading human
[2020-05-28 11:56:25,791] log.py->message():118 -- MESSAGE -- compiled file out of date: data/3dobjs/base.npz
[2020-05-28 11:56:25,823] log.py->warning():104 -- WARNING -- Prob

**Comment by justingeeslin** [comment]
What version of MacOS? And what version of MakeHuman? 

Since it's been a while, did you find a solution?

**Comment by rwbaer** [comment]
This is an outdated Mac that can not be upgraded to BigSur so closing.  Will reopen if critical to MH 1.2.0 or beyond.
